Fix scan key persistence issue
tillhub/scan-engine pull request #16
Opened 2024-03-05 15:44 UTC by shekar-allam

2024-03-06 12:47 UTC, djordjeh requested changes

2024-03-06 12:47 UTC, djordjeh commented on scan-engine/src/main/java/de/tillhub/scanengine/helper/ManagerBuilder.kt
> +    fun build(lifecycle: Lifecycle): T
Delete ManagerBuilder it's not needed anymore.

2024-03-06 15:30 UTC, djordjeh approved these changes

2024-03-07 07:55 UTC, SloInfinity approved these changes

2024-03-07 08:40 UTC, merged