[UNTIL-10894]Scan SDK tests
tillhub/scan-engine pull request #22
Opened 2024-06-17 13:26 UTC by shekar-allam

2024-06-18 11:38 UTC, SloInfinity approved these changes

2024-06-18 11:38 UTC, SloInfinity commented on scan-engine/src/test/java/de/tillhub/scanengine/data/ScannerManufacturerTest.kt
> +        ShadowBuild.setManufacturer("OTHER")
based on the code we want to test with something other than sunmi, without context I'd assume that "OTHER" has a proper mapping. 
I am suggesting to change "OTHER" to "NOT_SUNMI"

2024-06-20 07:23 UTC, djordjeh requested changes

2024-06-20 07:23 UTC, djordjeh commented on scan-engine/src/androidTest/java/de/tillhub/scanengine/barcode/SunmiBarcodeScannerTest.kt
> +        val intent = Intent(SunmiBarcodeScanner.ACTION_DATA_CODE_RECEIVED).apply {
In tests use hard coded string here "com.sunmi.scanner.ACTION_DATA_CODE_RECEIVED" we don't want to use variable from actual code.

2024-06-20 07:23 UTC, djordjeh commented on scan-engine/src/main/java/de/tillhub/scanengine/barcode/SunmiBarcodeScanner.kt
>          const val DATA = "data"
DATA can be private as well.

2024-06-20 10:57 UTC, djordjeh requested changes

2024-06-20 10:57 UTC, djordjeh commented on scan-engine/src/main/java/de/tillhub/scanengine/google/ui/GoogleScanningActivity.kt
> +        supportActionBar?.title = EMPTY
There is better way supportActionBar.setDisplayShowTitleEnabled(false) and you can delete EMPTY

2024-06-24 09:05 UTC, djordjeh reviewed
Since it will be some refactoring with additional bluetooth scanners, let merge this. After you finish refactoring tests will be addressed according to new code.

2024-06-24 09:05 UTC, djordjeh approved these changes

2024-06-25 06:37 UTC, merged