[UNTIL-12213] Generic bluetooth scanners
tillhub/scan-engine pull request #34
Opened 2024-10-16 06:58 UTC by shekar-allam

2024-10-18 08:52 UTC, SloInfinity approved these changes

2024-10-22 12:57 UTC, djordjeh requested changes

2024-10-22 12:58 UTC, djordjeh requested changes

2024-10-22 12:58 UTC, djordjeh commented on scan-engine/src/main/java/de/tillhub/scanengine/generic/GenericKeyEventScanner.kt
> +    override fun dispatchKeyEvent(event: KeyEvent, scanKey: String?) {
Write here small comment how this works and how do we distinguish between keyboards and scanners.

2024-10-24 09:34 UTC, djordjeh approved these changes

2024-10-24 09:44 UTC, merged